// <auto-generated />
using System;
using BookShare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookShare.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180925063831_DataContext20180925")]
    partial class DataContext20180925
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BookShare.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AminId");

                    b.Property<string>("Author");

                    b.Property<string>("CoverImage");

                    b.Property<DateTime>("CreateDT");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<string>("Publish");

                    b.Property<decimal>("RealPrice");

                    b.Property<string>("SubName");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
